baseURL = "https://example.com/"  # Change this to your real domain before deploying
languageCode = "en-us"
title = "My Personal Blog"
theme = "clarity"

# Controls how many posts are shown per page in list views
[pagination]
  pagerSize = 10

# Theme-specific parameters (Clarity)
[params]
  description = "Random thoughts, travel stories, and more."
  dateFormat = "2006-01-02"  # Format used in Go's date formatting
  toc = true                # Enable Table of Contents
  readingTime = true        # Show estimated reading time
  postMeta = ["date", "readingTime"]  # Show post metadata
  enableSearch = true       # Enable site-wide search
  author = "Deirdre Anne Hendrick"

# Allow raw HTML in Markdown
[markup.goldmark.renderer]
  unsafe = true

# Optional: explicitly declare the Markdown engine
[markup]
  defaultMarkdownHandler = "goldmark"

# Add taxonomy support (tags, categories)
[taxonomies]
  category = "categories"
  tag = "tags"

# Add support for additional output formats (RSS, search JSON)
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Optional: customize URLs for posts (e.g., /2025/05/my-post/)
[permalinks]
  posts = "/:year/:month/:slug/"

# Define top navigation menu
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
