baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Personal Blog"
theme = "clarity"

[permalinks]
  posts = "/posts/:slug/"

[pagination]
  pagerSize = 10

[params]
  description = "Random thoughts, travel stories, and more."
  dateFormat = "2006-01-02"
  toc = true
  readingTime = true
  postMeta = ["date", "readingTime"]
  enableSearch = true
  author = "Deirdre Anne Hendrick"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3