baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Personal Blog"
theme = "cleanwhite"

[params]
  header_image = "img/header_img.jpg"
  SEOTitle = "My Personal Blog"
  description = "Random thoughts, travel stories, and more."
  author = "Deirdre Anne Hendrick"
  slogan = "Clean writing, with a view."
  avatar = "img/avatar.jpg"
  github = ""
  twitter = ""
  email = "you@example.com"
  enableToc = true
  enableComments = false
  showAllPostsOnHomePage = true
  selfHosted = true

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
