baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Personal Blog"
theme = "PaperMod"

[permalinks]
  posts = "/posts/:slug/"

[pagination]
  pagerSize = 10

[params]
  description = "Random thoughts, travel stories, and more."
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  defaultTheme = "auto"
  author = "Deirdre Anne Hendrick"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3